apiVersion: 1

datasources:
  - name: Postgres
    uid: postgres_ds
    type: postgres
    access: proxy
    url: db:5432
    user: ${DB_USERNAME}
    secureJsonData:
      password: ${DB_PASSWORD}
    database: ${DB_NAME}